language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - pip install --quiet --upgrade pip codecov

install:
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
